# -*- coding: utf-8 -*-
"""process_tri_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxNHP3osullQXzKaCIS540OcVgIDdUiN
"""

import json
from datetime import datetime, timezone
from pathlib import Path
import pandas as pd

TXT_FILES = [
    'US_1a_2023.txt',
    'US_1a_2024.txt',
]
OUTPUT_DIR = Path('static data')

HOUSTON_COUNTIES = ['HARRIS', 'FORT BEND', 'BRAZORIA', 'GALVESTON', 'MONTGOMERY']

# 1-column right shift verified from sample rows
COL = {
    'trifd':        '8. DATE SIGNED',
    'facility':     '9. TRIFD',
    'city':         '11. FACILITY STREET',
    'county':       '12. FACILITY CITY',
    'state':        '13. FACILITY COUNTY',
    'zip':          '14. FACILITY STATE',
    'latitude':     '46. NAICS CODE 6',
    'longitude':    '47. LATITUDE',
    'chemical':     '80. TRI_CHEM_ID',
    'carcinogen':   '87. CARCINOGEN',
    'hap':          '86. HAZARDOUS AIR POLLUTANT - HAPS',
    'fugitive_lbs': '109. MAXIMUM AMOUNT ON SITE',
    'stack_lbs':    '113. FUGITIVE AIR EMISSIONS - BASIS OF ESTIMATE',
    'total_air':    '117. STACK AIR EMISSIONS - BASIS OF ESTIMATE',
}

def to_float(s):
    try: return float(str(s).replace(',', '').strip())
    except: return 0.0

def write_meta(csv_path: Path, source_url: str, rows: int, columns: list, notes: str = ''):
    meta = {
        'file': csv_path.name,
        'collected_at': datetime.now(timezone.utc).isoformat(),
        'rows': rows,
        'columns': columns,
        'source': {
            'name': 'EPA Toxic Release Inventory Basic Plus — File Type 1A',
            'url': source_url,
        },
        'notes': notes,
    }
    with open(csv_path.with_suffix('.meta.json'), 'w') as f:
        json.dump(meta, f, indent=2)

def process_year(txt_path: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    path = Path(txt_path)
    if not path.exists():
        print(f'File not found: {path}')
        return pd.DataFrame(), pd.DataFrame()

    chunks = []
    reader = pd.read_csv(
        path, sep='\t', encoding='latin-1', dtype=str,
        usecols=list(COL.values()), low_memory=False, chunksize=50_000,
    )
    for chunk in reader:
        tx = chunk[chunk[COL['state']].str.strip() == 'TX']
        if not tx.empty:
            chunks.append(tx)

    if not chunks:
        print(f'No Texas rows found in {path.name}')
        return pd.DataFrame(), pd.DataFrame()

    df = pd.concat(chunks, ignore_index=True).rename(columns={v: k for k, v in COL.items()})
    df = df[df['county'].str.upper().str.contains('|'.join(HOUSTON_COUNTIES), na=False)].copy()

    for col in ['latitude', 'longitude', 'fugitive_lbs', 'stack_lbs', 'total_air']:
        df[col] = df[col].apply(to_float)
    df['total_air_emissions_lbs'] = df['total_air']

    id_cols = ['trifd', 'facility', 'city', 'county', 'zip', 'latitude', 'longitude']
    facilities = (
        df.groupby(id_cols, as_index=False)
        .agg(
            total_air_emissions_lbs=('total_air_emissions_lbs', 'sum'),
            chemicals=('chemical', lambda x: '; '.join(sorted(x.dropna().unique())[:10])),
            has_carcinogen=('carcinogen', lambda x: 'YES' if 'YES' in x.values else 'NO'),
            has_hap=('hap', lambda x: 'YES' if 'YES' in x.values else 'NO'),
        )
        .sort_values('total_air_emissions_lbs', ascending=False)
        .reset_index(drop=True)
    )

    chem_cols = ['trifd', 'facility', 'zip', 'latitude', 'longitude',
                 'chemical', 'carcinogen', 'hap', 'fugitive_lbs', 'stack_lbs', 'total_air_emissions_lbs']
    chemicals = df[chem_cols][df['total_air_emissions_lbs'] > 0].copy()

    return facilities, chemicals

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
all_facilities, all_chemicals = [], []

for txt in TXT_FILES:
    year = Path(txt).stem.split('_')[-1]
    facilities, chemicals = process_year(txt)
    if facilities.empty:
        continue
    facilities['reporting_year'] = year
    chemicals['reporting_year']  = year
    all_facilities.append(facilities)
    all_chemicals.append(chemicals)
    print(f'{year}: {len(facilities)} facilities, {len(chemicals)} chemical records')

df_facilities = pd.concat(all_facilities, ignore_index=True) if all_facilities else pd.DataFrame()
df_chemicals  = pd.concat(all_chemicals,  ignore_index=True) if all_chemicals  else pd.DataFrame()

fac_path  = OUTPUT_DIR / 'tri_facilities_houston.csv'
chem_path = OUTPUT_DIR / 'tri_chemicals_houston.csv'

df_facilities.to_csv(fac_path,  index=False)
df_chemicals.to_csv(chem_path, index=False)

source_url = 'https://www.epa.gov/toxics-release-inventory-tri-program/tri-basic-plus-data-files-calendar-years'
years_note = f'Reporting years: {", ".join(str(Path(t).stem.split("_")[-1]) for t in TXT_FILES)}. Houston metro — Harris, Fort Bend, Brazoria, Galveston, Montgomery counties.'

write_meta(fac_path,  source_url, len(df_facilities), list(df_facilities.columns),  notes=years_note)
write_meta(chem_path, source_url, len(df_chemicals),  list(df_chemicals.columns),   notes=years_note)

print(f'\nSaved: {fac_path}  ({len(df_facilities)} rows)')
print(f'Saved: {chem_path} ({len(df_chemicals)} rows)')